# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3.3'

services:
  dockovpn:
    build: ./
    cap_add:
        - NET_ADMIN
    ports:
        - ${VPN_PORT}:1194/udp
        - ${API_PORT}:8080/tcp
    environment:
        HOST_ADDR: ${HOST_ADDR}
    restart: always
